// Code generated by packages/config/scripts/generate-contracts.mjs; DO NOT EDIT.
package productcatalog

const (
	ProductInfraLink  = "infra-link"
	ProductPlanerLink = "planer-link"
	ProductLokaLink   = "loka-link"
)

var IDs = []string{
	"infra-link",
	"planer-link",
	"loka-link",
}

func IsValidID(productID string) bool {
	for _, id := range IDs {
		if productID == id {
			return true
		}
	}

	return false
}
