// Code generated by packages/config/scripts/generate-contracts.mjs; DO NOT EDIT.
package adminaccess

import "sort"

const (
	RoleUser    = "user"
	RoleAdmin   = "admin"
	RoleSupport = "support"
	RoleAuditor = "auditor"
)

const (
	AdminRoleAdmin   = "admin"
	AdminRoleSupport = "support"
	AdminRoleAuditor = "auditor"
)

const (
	PermissionDashboardRead      = "admin.dashboard.read"
	PermissionUsersRead          = "admin.users.read"
	PermissionUsersUpdate        = "admin.users.update"
	PermissionUsersLock          = "admin.users.lock"
	PermissionUsersChangeRole    = "admin.users.change_role"
	PermissionAuthLogsRead       = "admin.auth_logs.read"
	PermissionSecurityEventsRead = "admin.security_events.read"
	PermissionSMTPSettingsRead   = "admin.smtp_settings.read"
	PermissionSMTPSettingsUpdate = "admin.smtp_settings.update"
	PermissionNotificationsRead  = "admin.notifications.read"
	PermissionAuditEntriesRead   = "admin.audit_entries.read"
)

var Roles = []string{
	"user",
	"admin",
	"support",
	"auditor",
}

var AdminRoles = []string{
	"admin",
	"support",
	"auditor",
}

var Permissions = []string{
	"admin.dashboard.read",
	"admin.users.read",
	"admin.users.update",
	"admin.users.lock",
	"admin.users.change_role",
	"admin.auth_logs.read",
	"admin.security_events.read",
	"admin.smtp_settings.read",
	"admin.smtp_settings.update",
	"admin.notifications.read",
	"admin.audit_entries.read",
}

var RolePermissions = map[string][]string{
	"admin": {
		"admin.dashboard.read",
		"admin.users.read",
		"admin.users.update",
		"admin.users.lock",
		"admin.users.change_role",
		"admin.auth_logs.read",
		"admin.security_events.read",
		"admin.smtp_settings.read",
		"admin.smtp_settings.update",
		"admin.notifications.read",
		"admin.audit_entries.read",
	},
	"support": {
		"admin.dashboard.read",
		"admin.users.read",
		"admin.users.update",
		"admin.users.lock",
		"admin.auth_logs.read",
		"admin.security_events.read",
		"admin.notifications.read",
	},
	"auditor": {
		"admin.dashboard.read",
		"admin.auth_logs.read",
		"admin.security_events.read",
		"admin.notifications.read",
		"admin.audit_entries.read",
	},
}

func IsRole(value string) bool {
	return contains(Roles, value)
}

func IsAdminRole(value string) bool {
	return contains(AdminRoles, value)
}

func IsPermission(value string) bool {
	return contains(Permissions, value)
}

func PermissionsForRole(role string) []string {
	permissions := RolePermissions[role]
	return append([]string{}, permissions...)
}

func PermissionsForRoles(roles []string) []string {
	grants := map[string]bool{}
	for _, role := range roles {
		for _, permission := range RolePermissions[role] {
			grants[permission] = true
		}
	}

	permissions := make([]string, 0, len(grants))
	for permission := range grants {
		permissions = append(permissions, permission)
	}
	sort.Strings(permissions)

	return permissions
}

func contains(values []string, value string) bool {
	for _, candidate := range values {
		if candidate == value {
			return true
		}
	}
	return false
}
