// Code generated by packages/config/scripts/generate-contracts.mjs; DO NOT EDIT.
import contract from './admin-access.json';

export const roles = contract.roles as unknown as readonly [
	'user',
	'admin',
	'support',
	'auditor'
];
export const adminRoles = contract.adminRoles as unknown as readonly [
	'admin',
	'support',
	'auditor'
];
export const adminPermissions = contract.permissions as unknown as readonly [
	'admin.dashboard.read',
	'admin.users.read',
	'admin.users.update',
	'admin.users.lock',
	'admin.users.change_role',
	'admin.auth_logs.read',
	'admin.security_events.read',
	'admin.smtp_settings.read',
	'admin.smtp_settings.update',
	'admin.notifications.read',
	'admin.audit_entries.read'
];

export type Role = (typeof roles)[number];
export type AdminRole = (typeof adminRoles)[number];
export type AdminPermission = (typeof adminPermissions)[number];

export const rolePermissions = {
	"admin": [
		"admin.dashboard.read",
		"admin.users.read",
		"admin.users.update",
		"admin.users.lock",
		"admin.users.change_role",
		"admin.auth_logs.read",
		"admin.security_events.read",
		"admin.smtp_settings.read",
		"admin.smtp_settings.update",
		"admin.notifications.read",
		"admin.audit_entries.read"
	],
	"support": [
		"admin.dashboard.read",
		"admin.users.read",
		"admin.users.update",
		"admin.users.lock",
		"admin.auth_logs.read",
		"admin.security_events.read",
		"admin.notifications.read"
	],
	"auditor": [
		"admin.dashboard.read",
		"admin.auth_logs.read",
		"admin.security_events.read",
		"admin.notifications.read",
		"admin.audit_entries.read"
	]
} as const satisfies Record<AdminRole, readonly AdminPermission[]>;

export function isRole(value: string): value is Role {
	return (roles as readonly string[]).includes(value);
}

export function isAdminRole(value: string): value is AdminRole {
	return (adminRoles as readonly string[]).includes(value);
}

export function isAdminPermission(value: string): value is AdminPermission {
	return (adminPermissions as readonly string[]).includes(value);
}
