// Code generated by packages/config/scripts/generate-contracts.mjs; DO NOT EDIT.
import catalog from './products.json';

export const products = catalog as unknown as readonly [
	{
		id: 'infra-link';
		name: 'Infra Link';
		appUrl: 'http://infra-link.codelinks.localhost';
		descriptionKey: 'products.infraLink.description';
	},
	{
		id: 'planer-link';
		name: 'Planer Link';
		appUrl: 'http://planer-link.codelinks.localhost';
		descriptionKey: 'products.planerLink.description';
	},
	{
		id: 'loka-link';
		name: 'Loka Link';
		appUrl: 'http://loka-link.codelinks.localhost';
		descriptionKey: 'products.lokaLink.description';
	}
];

export type ProductId = (typeof products)[number]['id'];
